/**
 * @description       : 
 * @author            : Sangram Keshari Upadhyaya
 * @group             : 
 * @last modified on  : 02-20-2024
 * @last modified by  : Sangram Keshari Upadhyaya
 * Modifications Log
 * Ver   Date         Author                      Modification
 * 1.0   02-20-2024   Sangram Keshari Upadhyaya   Initial Version
**/
public with sharing class ApexClassGitTest_Sangram {
    public ApexClassGitTest_Sangram() {

        System.debug('Version 1');
        
    }
}